### ISSUE TITLE
pre-commit hook to ensure the pinned Black on blacken-docs' hook is the same as Black's rev

### ISSUE THREAD

**Issue by pkoch** [asottile/blacken-docs#114]
I wrote this for a project of mine:

```yaml
    - repo: local
      hooks:
          - id: check-blacks-versions-matches-blacken-docs
            name: Check Black's versions matches blacken-doc's
            language: python
            entry: ./.git-hooks/check_blacks_versions_matches_blacken_docs.py
            additional_dependencies: [pyaml]
            files: ".pre-commit-config.yaml"
```

```python
#!/usr/bin/env python3
import yaml


def find_first(f):
    def find_first_(list_):
        if not (
            found := next(
                (e for e in list_ if f(e)),
                None,
            )
        ):
            raise RuntimeError(f"No element matches with {f}")

        return found

    return find_first_


def has_entry(key, value):
    def has_entry_(dict_):
        return dict_.get(key, None) == value

    return has_entry_


def key(key):
    def key_(dict_):
        if not (found := dict_.get(key, None)):
            raise RuntimeError(f'No "{key}"')

        return found

    return key_


def pipe_value(v, *fs):
    a = v

    for i, f in enumerate(fs, 1):
        try:
            a = f(a)
        except Exception as e:
            raise RuntimeError(f"Exception on {i}th function") from e

    return a


with open(".pre-commit-config.yaml") as f:
    contents = yaml.load(f, Loader=yaml.FullLoader)

repos = key("repos")(contents)

black_rev = pipe_value(
    repos,
    find_first(has_entry("repo", "https://github.com/psf/black")),
    key("rev"),
)

pin_prefix = "black=="
blacks_pin = pipe_value(
    repos,
    find_first(has_entry("repo", "https://github.com/asottile/blacken-docs")),
    key("hooks"),
    find_first(has_entry("id", "blacken-docs")),
    key("additional_dependencies"),
    find_first(lambda e: e.startswith(pin_prefix)),
)

if blacks_pin != f"{pin_prefix}{black_rev}":
    raise RuntimeError(
        f"Black's pin in blackend-docs's additional_dependencies (`{blacks_pin}`) doesn't match black's repo rev (`{black_rev}`)."
    )

# All good, can't complain! 👍
```

This feels like something that most people would want. Maybe we want to get a variation of this in?

The code is a bunch unpythonic, maybe re-writing it is due.
