### ISSUE TITLE
If I use blacken-docs, does that mean I don't need to use black anymore

### ISSUE THREAD

**Issue by xiaohuazi123** [asottile/blacken-docs#47]
I see  pre-committ-config.yaml is the configuration file where you can set the category of files that use blacken-docs

For example, the following file instructs blacken-docs to format files with the suffixes RST, md, py, markdown, Tex
```yaml
repos:
  - repo: https://github.com/psf/black
    rev: stable  
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/asottile/blacken-docs
    rev: master
    hooks:
    -   id: blacken-docs
        language: python
        files: '\.(rst|md|markdown|py|tex)$'
```

Does that mean I can remove black and just keep blacken-docs?
just like this:
```yaml
repos:
  - repo: https://github.com/asottile/blacken-docs
    rev: master
    hooks:
    -   id: blacken-docs
        language: python
        files: '\.(rst|md|markdown|py|tex)$'
```
