### ISSUE TITLE
The docstring in the python file is not formatted by blacken-docs

### ISSUE THREAD

**Issue by xiaohuazi123** [asottile/blacken-docs#50]
Hi ,All
 I have set up the format python file, and the docstring in the python file is not formatted by blacken-docs, why is that

This is my.pre-committ-config.yaml configuration file
```
repos:
  - repo: https://github.com/psf/black
    rev: stable  
    hooks:
      - id: black
        language_version: python3.7
        args: [--line-length=120]
        args: [--skip-string-normalization]

  - repo: https://github.com/asottile/blacken-docs
    rev: master
    hooks:
      - id: blacken-docs
        language: python
        args: [--line-length=120]
        args: [--skip-string-normalization]
        files: '\.(rst|md|markdown|py|tex)$'

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master  
    hooks:
      - id: isort
```
  

This is my Python file
```
#!/usr/bin/env python.exe
# -*- coding:utf-8 -*-
# @Author : huazai
# @Time : 2020/3/24 16:36
# @File : tt.py
# @Description :


import os
import re
import smtplib
import subprocess
import sys


def foo(a: str, b: str) -> str:
    c = None  # type:str
    c = a
    return c


class Zabbix_api():
    """Form a complex number.
    Keyword arguments:
    print(  len(  data))
    print(len(json.dumps(data)))
    aa= json.dumps(data)
    print(aa   )
    """

```
As you can see, after executing blacken-docs, the docstring in the Zabbix_api class is not formatted.

Thanks.
